name: MBM News Bot

on:
  schedule:
    - cron: '0 * * * *' # 每小時執行一次
  workflow_dispatch: # 允許手動執行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python main.py

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # 檢查檔案是否存在，不存在則建立空的
          touch last_news.txt
          git add last_news.txt
          # 只有在有變動時才 commit，避免報錯
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update last news" && git push)

          git commit -m "Update last news" || exit 0
          git push
